name: green-condor-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - atlite>=0.2.11
  - geopandas>=0.14
  - geodatasets>=2023.3.0
  - numpy>=1.26
  - pandas>=2.2
  - xarray>=2024.3
  - dask>=2024.5
  - zarr>=2.16
  - shapely>=2.0
  - rasterio>=1.3
  - pyproj>=3.6
  - bottleneck>=1.3
  - scipy>=1.11
  - netcdf4>=1.6
  - tqdm>=4.66
